language: python
python:
  - "3.6"
cache: pip
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
env:
  CODECOV_TOKEN="8ed8569c-fb05-4a1c-a0b7-30c3915bb266"